---
- name: Install Linux packages
  when: (ansible_system | lower) == 'linux'
  vars:
    json_packages: >-
      {{ packages | to_json | from_json }}

  block:
    - name: System packages
      vars:
        # Extracts package names based on the current OS family for overridden packages
        os_packages: >-
          {{ json_packages | community.general.json_query('[?!snap || ' + os_family + '][' + os_family + ' || name][]') }}
      block:
        - name: Packages to install
          ansible.builtin.debug:
            var: os_packages

        - name: Install Arch Linux packages
          when: os_family == 'archlinux'
          block:
            - name: Install repository packages
              ansible.builtin.pacman:
                name: >-
                  {{ os_packages | select('string') }}
                update_cache: true
              become: true

            - name: Make sure that yay is installed
              kewlfft.aur.aur:
                use: makepkg
                name:
                  - yay
                state: present

            - name: Install core and AUR packages
              kewlfft.aur.aur:
                use: yay
                name: >-
                  {{ os_packages | selectattr('aur', 'defined') | map(attribute='aur') }}
                state: present

        - name: Install Debian-based packages
          when: os_family == 'debian'
          block:
            - name: Add apt repositories
              ansible.builtin.debug:
                msg: "TODO: Add repositories for packages that aren't available in the default repos"

            - name: Install packages
              ansible.builtin.apt:
                name: >-
                  {{ os_packages }}
                update_cache: true
                state: present
              become: true

    - name: Snaps
      vars:
        snap_packages: >-
          {{ json_packages | community.general.json_query('[?snap && !' + os_family + '][snap][]') }}

      block:
        - name: Snaps to install
          ansible.builtin.debug:
            var: snap_packages

        - name: Make sure that snapd is installed in Arch Linux
          when: os_family == 'archlinux'
          kewlfft.aur.aur:
            name:
              - snapd
            use: yay
            state: present

        - name: Make sure snapd.service is running
          ansible.builtin.systemd_service:
            name: snapd.service
            state: started
          become: true

        - name: Install snap packages
          community.general.snap:
            name: >-
              {{ snap_packages }}
            state: present

- name: Install Homebrew packages
  when: os_family in ['darwin', 'debian']

  block:
    - name: Check if Homebrew is installed
      ansible.builtin.command: brew --version
      register: brew_installed
      ignore_errors: true

    - name: Check for Brewfile
      ansible.builtin.stat:
        path: "~/.Brewfile"
      register: brewfile_exists

    - name: Install from Brewfile
      ansible.builtin.command: brew bundle --global
      when: brew_installed.rc == 0 and brewfile_exists.stat.exists
