show_actions = false
only_search_title = false
history = true

single_instance_apps = [
    "code",
    "discord",
    "ferdium",
    "gnome-calendar",
    "insomnia",
    "mailspring",
    "notion-app",
    "obsidian",
    "proton-mail",
    "slack",
    "spotify",
    "steam",
    "telegram-desktop",
]
