-- GENERATED by wallust from templates/hyprland.lua -- do not edit.
--
-- The Hyprland palette, for the Lua config (hyprland.lua and everything it
-- requires). vars/colors.conf is the hyprlang twin of this file, for hyprlock
-- and the other hypr* daemons; both are rewritten on every wallust run.
--
-- Each color is exposed opaque as `<name>` and at 10%..90% as
-- `<name>_alpha1..9`.

return {
  cursor = "rgb({{ cursor | rgb }})",
{% for c in colors %}
{%- set name = "color" + (loop.index0 | string) -%}
{% if loop.index == loop.length -1 %}
{%- set name = "background" -%}
{%- elif loop.index == loop.length %}
{%- set name = "foreground" -%}
{%- endif %}
  -- {{ name }}: {{ c }}
  {{ name }} = "rgb({{ c | rgb }})",
{%- for alpha in range(1, 10) %}
  {{ name }}_alpha{{ alpha }} = "rgba({{ c | strip }}{{ (alpha * 10) | alpha_hexa }})",
{%- endfor %}
{% endfor -%}
}
