# vim:fileencoding=utf-8:ft=tmux:foldmethod=marker

set -gF @ansi_cleanup "#{d:current_file}/scripts/ansi-cleanup"
set -gF @ansi_to_tmux "#{d:current_file}/scripts/ansi-to-tmux"

source ~/.config/tmux/options.tmux
source ~/.config/tmux/keymaps.tmux
source ~/.config/tmux/plugins.tmux
