prSections:
  - title: My Pull Requests
    filters: is:open archived:false author:@me
  - title: Participating
    filters: is:open archived:false -author:@me involves:@me
  - title: Needs My Review
    filters: is:open archived:false review-requested:@me

issuesSections:
  - title: Assigned
    filters: is:open archived:false assignee:@me
  - title: Participating
    filters: is:open archived:false -author:@me -assignee:@me involves:@me
  - title: Created
    filters: is:open archived:false author:@me

defaults:
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true
    width: 60
  view: prs

repoPaths:
  aelesbao/*: ~/workspace/sandbox/*
  archway-network/*: ~/workspace/archway/*

keybindings:
  prs:
    - key: C
      command: >
        cd {{.RepoPath}} &&
        gh pr checkout {{.PrNumber}}
    - key: v
      command: >
        cd {{.RepoPath}} &&
        gh pr checkout {{.PrNumber}} &&
        code .
