prSections:
  - title: My Pull Requests
    filters: is:open archived:false author:@me
  - title: Participating
    filters: is:open archived:false -author:@me involves:@me
  - title: Needs My Review
    filters: is:open archived:false review-requested:@me
  - title: DevX
    filters: is:open archived:false project:archway-network/11
  - title: NetX
    filters: is:open archived:false project:archway-network/10

issuesSections:
  - title: Assigned
    filters: is:open archived:false assignee:@me
  - title: Participating
    filters: is:open archived:false -author:@me -assignee:@me involves:@me
  - title: DevX
    filters: is:open archived:false project:archway-network/11
  - title: NetX
    filters: is:open archived:false project:archway-network/10
  - title: Created
    filters: is:open archived:false author:@me

defaults:
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true
    width: 60
  view: issues
