#!/bin/sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

. "$SCRIPT_DIR/util.sh"

enable_script_addition=true

if [ $enable_script_addition = true ] && is_system_protection_disabled; then
    echo "Installing Yabai script-addition"
    yabai -m signal --add event=dock_did_restart label="re-load script addition" action="sudo yabai --load-sa"
    sudo yabai --load-sa
fi

# default layout (can be bsp, stack or float)
if has_ultrawide_display; then
    yabai -m config layout bsp
else
    yabai -m config layout stack
fi

yabai -m config \
    insert_feedback_color  0x66f4b8e4 \
    split_ratio            0.50 \
    split_type             auto

# balance the window tree upon change, so that all windows occupy the same area
yabai -m config auto_balance off

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config \
    window_placement     second_child \
    window_zoom_persist  on

# Specify which display a newly created window should be managed in.
# default: The display in which the window is created (standard macOS behaviour)
# focused: The display that has focus when the window is created
# cursor: The display that currently holds the mouse cursor
yabai -m config window_origin_display focused

# padding between windows
yabai -m config \
    top_padding 5 \
    bottom_padding 5 \
    left_padding 5 \
    right_padding 5 \
    window_gap 5

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:20:0

# mouse settings
yabai -m config \
    mouse_follows_focus off \
    focus_follows_mouse off \
    mouse_modifier ctrl \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action stack

# extra settings that require System Integrity Protection to be partialy disabled
if [ $enable_script_addition = true ] && is_system_protection_disabled; then
    yabai -m config \
        window_shadow                on \
        window_animation_duration    0.0 \
        window_opacity               off \
        window_opacity_duration      0.0 \
        active_window_opacity        1.0 \
        normal_window_opacity        0.95
fi

. "$SCRIPT_DIR/spaces.sh"
. "$SCRIPT_DIR/rules.sh"

echo "yabai configuration loaded.."

# vim:ft=sh:foldmethod=marker
