# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#RemoveMake
SudoLoop
#UseAsk
#SaveChanges
CombinedUpgrade
CleanAfter
UpgradeMenu
NewsOnUpgrade
BatchInstall

#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

CompletionInterval = 1

#
# Binary OPTIONS
#
[bin]
FileManager = yazi
#MFlags = --skippgpcheck
#Sudo = doas
