#!/bin/zsh

set -euo pipefail -x

direction="${1:-next}"

if [[ "$direction" != "next" && "$direction" != "prev" ]]; then
  echo "Invalid direction: $direction."
  echo "Usage: $0 [next|prev]"
  exit 1
fi

conf_file="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprpaper.conf"

# NOTE: this scripts will set the same wallpaper on all monitors.

function get-current-wallpaper() {
  # Try to get the current wallpaper from hyprpaper.conf
  if [[ -f "$conf_file" ]]; then
    local path_line="$(grep -E '^\s*path\s*=' "$conf_file" || true)"
    if [[ -n "$path_line" ]]; then
      local path=$(echo "$path_line" | sed -E 's/^\s*path\s*=\s*(.*)\s*$/\1/')
      if [[ -f "$path" ]]; then
        echo "$path"
        return
      fi
    fi
  fi

  # If all else fails, return empty
  echo ""
}

# Get a list of all wallpapers
wallpapers_dir="${WALLPAPERS_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/wallpapers}"
wallpapers=( $(fd --type f . "$wallpapers_dir") )

# Gets the active wallpaper
current="$(get-current-wallpaper)"
if [[ -z "$current" ]]; then
  echo "No active wallpaper found. Exiting."
  exit
fi

# Gets the wallpaper index, increment it, and check for array overflow
[[ "$direction" == "next" ]] && dir=1 || dir=-1
next_idx=$((
  current = ${wallpapers[(ie)$current]},
  next = current + dir,
  next < 1 ? ${#wallpapers[@]} : (next > ${#wallpapers[@]} ? 1 : next)
))

# Apply the the next wallpaper in the list
wallpaper="${wallpapers[$next_idx]}"
notify-send -e -t 2000 -u low -i cs-desktop -a "hyprpaper" "Hyprpaper" "Wallpaper set to ${wallpaper:t}"
hyprctl hyprpaper wallpaper ,"$wallpaper"

# Updates ~/.config/hypr/hyprpaper.conf with currently active wallpaper
cat <<EOL >! ${conf_file}
wallpaper {
    monitor =
    path = ${wallpaper}
}
EOL
