#!/bin/zsh

set -euo pipefail -x

direction="${1:-next}"

if [[ "$direction" != "next" && "$direction" != "prev" ]]; then
  echo "Invalid direction: $direction."
  echo "Usage: $0 [next|prev]"
  exit 1
fi

# NOTE: this scripts will set the same wallpaper on all monitors.

# Get a list of all wallpapers
wallpapers_dir="${WALLPAPERS_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/wallpapers}"
wallpapers=( $(fd --type f . "$wallpapers_dir") )

# Gets the active wallpaper
current="$(hyprctl hyprpaper listactive | grep -oP '(?<= = ).*' | uniq || echo '')"
if [[ -z "$current" ]]; then
  echo "No active wallpaper found. Exiting."
  exit
fi

# Gets the wallpaper index, increment it, and check for array overflow
[[ "$direction" == "next" ]] && dir=1 || dir=-1
next_idx=$((
  current = ${wallpapers[(ie)$current]},
  next = current + dir,
  next < 1 ? ${#wallpapers[@]} : (next > ${#wallpapers[@]} ? 1 : next)
))

# Apply the the next wallpaper in the list
wallpaper="${wallpapers[$next_idx]}"
notify-send -e -t 2000 -u low -i cs-desktop -a "hyprpaper" "Hyprpaper" "Wallpaper set to ${wallpaper:t}"
hyprctl hyprpaper reload ,"$wallpaper"

# Updates ~/.config/hypr/hyprpaper.conf with currently active wallpaper
cat <<EOL >! ~/.config/hypr/hyprpaper.conf
preload = ${wallpaper}
wallpaper = , ${wallpaper}
EOL
