#!/bin/zsh

set -euo pipefail

declare service="$1"
if [[ -z "$service" ]]; then
  echo "Usage: $0 <service-name>"
  exit 1
fi

systemctl --user restart "${service}.service"
notify-send -e -u low "systemd" "${service} service restarted"
