disableStartupPopups: true

# one of: 'prompt' | 'create' | 'skip' | 'quit'
notARepository: "quit"

git:
  commit:
    signOff: true

  merging:
    args: "--no-ff"

  parseEmoji: true

gui:
  showRandomTip: false
  # show commit hashes alongside branch names
  showBranchCommitHash: true
  # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  nerdFontsVersion: "3"
  # for skipping the confirmation before launching the reword editor
  skipRewordInEditorWarning: true

  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

