disableStartupPopups: true

# one of: 'prompt' | 'create' | 'skip' | 'quit'
notARepository: "quit"

git:
  commit:
    signOff: false

  merging:
    args: "--no-ff"

  parseEmoji: true

  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  showRandomTip: false
  # show commit hashes alongside branch names
  showBranchCommitHash: true
  # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  nerdFontsVersion: "3"
  # for skipping the confirmation before launching the reword editor
  skipRewordInEditorWarning: true

  # https://pkg.go.dev/time#Time.Format
  timeFormat: "2006-01-02 15:04:05"
  shortTimeFormat: "15:04"

refresher:
  refreshInterval: 10 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
  fetchInterval: 600 # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.

update:
  method: never

customCommands:
  - key: "C"
    context: "files"
    description: "Create new conventional commit"
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "build"
            description: "Changes that affect the build system or external dependencies"
            value: "build"
          - name: "feat"
            description: "A new feature"
            value: "feat"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "ci"
            description: "Changes to CI configuration files and scripts"
            value: "ci"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
      - type: "input"
        title: "Scope (without parens)"
        key: "Scope"
        initialValue: ""
      - type: "input"
        title: "Breaking change - Add '!'"
        key: "Breaking"
        initialValue: ""
      - type: "input"
        title: "message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        key: "Confirm"
        title: "Commit"
        body: "Are you sure you want to commit?"
    command: "git commit --message '{{.Form.Type}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}{{.Form.Breaking}}: {{.Form.Message}}'"
    loadingText: "Creating conventional commit..."

  - key: "<c-p>"
    context: "files"
    description: "Create a pull request on GitHub"
    prompts:
      - type: "input"
        title: "Base branch"
        key: "Base"
        initialValue: "main"
    command: "hub pull-request --base '{{.Form.Base}}' --push --browse --edit"
    loadingText: "Creating pull request on GitHub"
    subprocess: true
