-- Emits hyprlang `$name = value` files.
--
-- The rest of the hypr ecosystem (hyprlock, hypridle, hyprpaper, ...) is still
-- hyprlang-only, so anything they need to share with the compositor config has
-- to be written back out in the old format.

local M = {}

--- Write `entries` to `path` as hyprlang variable assignments.
---
--- Each entry is `{ name, value }`, or `{ name, value, heading }` to emit a
--- blank line and a `# heading` comment before it. Returns true, or false plus
--- an error message.
---@param path string
---@param entries table[]
---@param source string  what generated this, named in the header
function M.write_vars(path, entries, source)
  local out = {
    "# GENERATED by " .. source .. " -- do not edit.",
    "# Run scripts/gen-hyprlang-vars after changing it.",
    "#",
    "# Exists because hyprlock and the other hypr* daemons are still hyprlang",
    "# and cannot read hyprland.lua.",
    "",
  }

  for _, entry in ipairs(entries) do
    local name, value, heading = entry[1], entry[2], entry[3]
    if heading then
      out[#out + 1] = ""
      out[#out + 1] = "# " .. heading
    end
    out[#out + 1] = "$" .. name .. " = " .. value
  end

  out[#out + 1] = ""

  local file, err = io.open(path, "w")
  if not file then
    return false, err
  end

  file:write(table.concat(out, "\n"))
  file:close()

  return true
end

return M
