# Refer to https://wiki.hyprland.org/Configuring/Variables/

# Launchers
$launcher         = ~/.local/bin/walker-launch
$switcher         = ~/.local/bin/walker-launch -m windows
$calc             = ~/.local/bin/walker-launch -m calc
$emoji            = ~/.local/bin/walker-launch -m symbols
$clipboardHistory = ~/.local/bin/walker-launch -m clipboard

# uses proposed xdg-terminal-exec
$terminal = uwsm app -- ghostty +new-window
$fileManager = uwsm app -- thunar --window
$passwordManager = uwsm app -a 1password-quick-access -- 1password --quick-access

$notificationHistory  = swaync-client --skip-wait --toggle-panel
$dismissNotifications = swaync-client --skip-wait --hide-all
$toggleDND            = swaync-client --skip-wait --toggle-dnd

$colorPicker = uwsm app -- hyprpicker --autocopy --lowercase-hex
$screenshot  = uwsm app -- hyprshot -m region -o ~/Pictures/Screenshots

# Volume control commands
# $volUp      = wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
# $volDown    = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
# $volMute    = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# $volMicMute = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Alternative volume control commands with notifications
# $volUp   = set-volume up 5
# $volDown = set-volume down 5
# $volMute = set-volume mute

# playerctl commands
$playerNext     = playerctl next
$playerForward  = playerctl position +5
$playerPrevious = playerctl previous
$playerRewind   = playerctl position -5
$playerPlay     = playerctl play-pause
$playerPause    = playerctl play-pause

# Brightness control commands
# $brightUp = brightnessctl s 10%+
# $brightDown = brightnessctl s 10%-

# SwayOSD
$volUp      = swayosd-client --output-volume +3 --max-volume 100
$volDown    = swayosd-client --output-volume -3 --max-volume 100
$volMute    = swayosd-client --output-volume mute-toggle

$volMicUp   = swayosd-client --input-volume +3 --max-volume 100
$volMicDown = swayosd-client --input-volume -3 --max-volume 100
$volMicMute = swayosd-client --input-volume mute-toggle

$playerNext     = swayosd-client --playerctl next
$playerPrevious = swayosd-client --playerctl prev
$playerPlay     = swayosd-client --playerctl play-pause
$playerPause    = swayosd-client --playerctl play-pause

$brightUp   = swayosd-client --brightness raise
$brightDown = swayosd-client --brightness lower

# Productivity tools
$todo = uwsm app -- flatpak run --command=io.github.alainm23.planify.quick-add io.github.alainm23.planify
