# Modified from https://github.com/HyDE-Project/hyde-themes/blob/Tokyo-Night/Configs/.config/hyde/themes/Tokyo%20Night/hypr.theme

$GTK_THEME = Tokyonight-Purple-Dark
$ICON_THEME = candy-icons
$COLOR_SCHEME = prefer-dark

# Optional: The varibles above will be set automatically when the theme is loaded
# This exec commands will soon be deprecated

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
  gaps_in = 4
  gaps_out = 8
  border_size = 1

  col.active_border = $color5 $color6 45deg 
  col.inactive_border = $color8_alpha8 $color7_alpha8 45deg
}

group {
  col.border_active = $color5 $color6 45deg
  col.border_inactive = $color8_alpha8 $color7_alpha8 45deg
  col.border_locked_active = $color5 $color6 45deg 
  col.border_locked_inactive = $color8_alpha8 $color7_alpha8 45deg

  groupbar {
    font_size = 13

    height = 22

    gradients = false
    gradient_rounding = 5

    rounding = 5
    indicator_gap = 0
    indicator_height = 2

    gaps_in = 2
    gaps_out = 2
    keep_upper_gap = false

    text_color = $foreground
    col.active = $color6_alpha8
    col.inactive = $color6_alpha2
    col.locked_active = $color1_alpha9
    col.locked_inactive = $color1_alpha3
  }
}

decoration {
  rounding = 6
  rounding_power = 4

  shadow {
    enabled = false
    color = $background_alpha7
  }

  blur {
    enabled = true
    size = 12
    passes = 3
    xray = true
    noise = 0.05
    ignore_opacity = true
  }

}

misc {
  background_color = $background
}

plugin {
  hy3 {
    tabs {
      # active tab bar segment colors
      col.active = $color0_alpha9 # default: rgba(33ccff40)
      col.active.border = $color5 # default: rgba(33ccffee)
      col.active.text = $foreground # default: rgba(ffffffff)

      # focused tab bar segment colors (focused node in unfocused container)
      col.focused = $background_alpha9 # default: rgba(60606040)
      col.focused.border = $color5_alpha5 # default: rgba(808080ee)
      col.focused.text = $foreground # default: rgba(ffffffff)

      # inactive tab bar segment colors
      col.inactive = $background_alpha9 # default: rgba(30303020)
      col.inactive.border = $color8_alpha8 # default: rgba(606060aa)
      col.inactive.text = $color7 # default: rgba(ffffffff)

      # urgent tab bar segment colors
      col.urgent = $background_alpha9 # default: rgba(ff223340)
      col.urgent.border = $color1 # default: rgba(ff2233ee)
      col.urgent.text = $foreground # default: rgba(ffffffff)

      # locked tab bar segment colors
      col.locked = $background_alpha9 # default: rgba(90903340)
      col.locked.border = $color3 # default: rgba(909033ee)
      col.locked.text = $foreground # default: rgba(ffffffff)
    }
  }
}

layerrule = blur,waybar
