# Modified from https://github.com/HyDE-Project/hyde-themes/blob/Tokyo-Night/Configs/.config/hyde/themes/Tokyo%20Night/hypr.theme

# $GTK_THEME = Tokyonight-Purple-Dark
# $ICON_THEME = candy-icons
# $COLOR_SCHEME = prefer-dark
#
# exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
# exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
# exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

misc {
  background_color = $background
}

general {
  col.active_border =   $color5 $color6 45deg 
  col.inactive_border = $color5_alpha5 $color6_alpha5 45deg
}

group {
  col.border_active =          $color5 $color6 45deg
  col.border_inactive =        $color5_alpha5 $color6_alpha5 45deg
  col.border_locked_active =   $color5 $color6 45deg
  col.border_locked_inactive = $color5_alpha5 $color6_alpha5 45deg

  groupbar {
    text_color =                 $foreground
    text_color_inactive =        $foreground_alpha6
    text_color_locked_active =   $color11
    text_color_locked_inactive = $color11_alpha6

    col.active =          $color0_alpha8
    col.inactive =        $background_alpha2
    col.locked_active =   $color0_alpha8
    col.locked_inactive = $background_alpha2
  }
}

decoration {
  shadow {
    color = $background_alpha8
  }
}

plugin {
  hy3 {
    tabs {
      # active tab bar segment colors
      col.active = $color0_alpha9
      col.active.border = $color5
      col.active.text = $foreground

      # focused tab bar segment colors (focused node in unfocused container)
      col.focused = $background_alpha9
      col.focused.border = $color5_alpha5
      col.focused.text = $foreground

      # inactive tab bar segment colors
      col.inactive = $background_alpha9
      col.inactive.border = $color8_alpha8
      col.inactive.text = $color7

      # urgent tab bar segment colors
      col.urgent = $background_alpha9
      col.urgent.border = $color1
      col.urgent.text = $foreground

      # locked tab bar segment colors
      col.locked = $background_alpha9
      col.locked.border = $color3
      col.locked.text = $foreground
    }
  }
}
