k9s:
  cluster: colima
  readOnly: false
  namespace:
    active: indexer
    lockFavorites: false
    favorites:
      - all
      - default
      - indexer
  view:
    active: pods
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
