k9s:
  cluster: colima
  readOnly: false
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
      - ambur-indexer
      - circulating-supply
  view:
    active: pods
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
