# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Core components (authentication, lock screen, notification daemon)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd --all
# Fix apps that take a really long time to open
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# SwayOSD
exec-once = uwsm app -- swayosd-server

# Removable disk automounter using udisks
exec-once = udiskie

# Reload Hyprland plugins
exec-once = hyprpm reload

# Open to the system tray without showing the main window
exec-once = sleep 5 && uwsm app -- 1password --silent

# KDE Connect indicator in the system tray
exec-once = uwsm app -- org.kde.kdeconnect.nonplasma.desktop

# LM Studio as a service
exec-once = uwsm app -- lmstudio --run-as-service

exec-once = uwsm app -- Mailspring.desktop
exec-once = uwsm app -- org.gnome.Calendar.desktop
exec-once = uwsm app -- ferdium.desktop
exec-once = uwsm app -- signal-desktop.desktop
exec-once = uwsm app -- com.mitchellh.ghostty.desktop
exec-once = uwsm app -- obsidian.desktop
exec-once = uwsm app -- slack.desktop
exec-once = uwsm app -- brave-browser.desktop
exec-once = uwsm app -- brave-talus.desktop
