binds {
    # If enabled, changing the active workspace (including to itself) will hide
    # the special workspace on the monitor where the newly active workspace resides.
    hide_special_on_workspace_change = true

    # Whether switching workspaces should center the cursor on the workspace (0)
    # or on the last active window for that workspace (1)
    workspace_center_on = 1
}
