# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    # Set the global default font to render the text including
    # debug fps/notification, config error messages and etc.
    font_family = $font_ui

    # Focus an app that requests to be focused (an activate request)
    focus_on_activate = true
    # Set to 0 or 1 to disable the anime mascot wallpapers
    force_default_wallpaper = 0
    # If true disables the random hyprland logo / anime girl background. :(
    disable_hyprland_logo = true

    # controls the VRR (Adaptive Sync) of your monitors.
    # 0 - off
    # 1 - on
    # 2 - fullscreen only
    # 3 - fullscreen with video or game content type
    vrr = 3
}

ecosystem {
  no_update_news = false
  no_donation_nag = true
}

render:cm_sdr_eotf = 3
