# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Smart gaps
windowrule = match:workspace f[1], match:float on, border_size 0, rounding 0

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Allows size persistence between application launches for floating windows
windowrule = match:float on, persistent_size true

# Floating apps
windowrule = match:class 1password, float on
windowrule = match:class evolution-alarm-notify, float on
windowrule = match:class blueman-applet, float on
windowrule = match:class re.sonny.Junction, float on
windowrule = match:class gcm-picker, float on
windowrule = match:class org.gnome.Calculator, float on
windowrule = match:class io.github.aelesbao.Kairo, float on

# Browser
windowrule = match:initial_class ^(brave-|firefox)(.*)$, tag +browser
windowrule = match:initial_title ^(MetaMask|Keplr|Phantom Wallet|Slush)(.*)$, match:tag browser, float on

# Email
windowrule = match:class ^(Mailspring|me.proton.Mail|org.gnome.Evolution), tag +email

# Games
windowrule = match:initial_class ^(steam_.*)$, content game, tag +game
windowrule = match:initial_class ^(steam|net.lutris.Lutris)$, tag +game
windowrule = match:class steam, match:title (Steam Settings), float on
# windowrule = match:content game, tag +game
windowrule = match:tag game, workspace 6, immediate on

# Terminal
windowrule = match:class ^(com.mitchellh.ghostty|kitty|alacritty|foot|wezterm|org.gnome.Terminal), tag +term
windowrule = match:tag term, no_blur on, opaque on

# Media
windowrule = match:class ^([Ss]potify|de.haeckerfelix.Shortwave|vlc|mpv)$, tag +media
# windowrule = match:content video, tag +media
windowrule = match:tag media, workspace special:media

# Communication
windowrule = match:class ^(signal|org.telegram.desktop|ferdium), tag +comms
windowrule = match:tag comms, workspace special:comms
windowrule = match:class signal, match:title (Signal Desktop Preferences), float on

windowrule = match:class ^(discord), workspace special:discord

# Fix pinentry losing focus
windowrule = match:class (pinentry-)(.*), stay_focused on, pin on
windowrule = match:class 1password, match:title (Quick Access)(.*), stay_focused on, pin on
# Secure input
windowrule = match:class ^(pinentry-.*|1password), no_screen_share on

# Fix some dragging issues with XWayland
windowrule = match:float on, match:fullscreen off, match:pin off, match:class ^$, match:title ^$, match:xwayland on, no_focus on

# Initial workspace
windowrule = match:class org.gnome.Calendar, workspace 1
windowrule = match:tag email, workspace 1
windowrule = match:class ^(Todoist), workspace 1
windowrule = match:title (Personal|Taxes|Home Lab|Crypto|Shopping), match:tag browser, workspace 2
windowrule = match:class obsidian, workspace 2
windowrule = match:title Development, match:tag browser, workspace 3
windowrule = match:tag term, workspace 3
windowrule = match:class [Ss]lack, workspace 4
windowrule = match:title (Job Search|Interviews), match:tag browser, workspace 4

# Groups
windowrule = match:tag email, group set lock invade
windowrule = match:title (Personal|Taxes|Home Lab|Crypto|Shopping), match:tag browser, group set lock invade
