[cargo-new]
email = "aelesbao@users.noreply.github.com"

[alias]
gen = "generate"
nt = "nextest run"

[unstable]
sparse-registry = true

[target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.mold"]
