background = rgb(26,27,38)
text = rgb(192,202,245)
base = rgb(187,154,247)
alternate_base =rgb(42,195,222) 
bright_text =rgb(125,207,255) 
accent = rgb(187,154,247)
accent_secondary =rgb(42,195,222) 

# font size for H1 (default: 19)
h1_size = 19
# font size for H2 (default: 15)
h2_size = 16
# font size for H3 (default: 13)
h3_size = 14
# font size for regular text elements (default: 11)
font_size = 12
# font size for small text elements (default: 10)
small_font_size = 10

# name of the icon theme to use, empty for “the first found” (default: empty)
icon_theme = candy-icons
