layerrule {
    name = waybar-blur
    blur = on
    ignore_alpha = 0.5
    match:namespace = waybar
}

layerrule {
    name = rofi-fx
    blur = on
    ignore_alpha = 0.5
    dim_around = on
    match:namespace = rofi
}

layerrule {
    name = swaync-control-center-fx
    blur = on
    ignore_alpha = 0
    dim_around = on
    match:namespace = swaync-control-center
}

layerrule {
    name = swaync-notification-window-fx
    ignore_alpha = 0
    match:namespace = swaync-notification-window
}

layerrule {
    name = no-anim-for-selection
    no_anim = on
    match:namespace = selection
}
