# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Smart gaps
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0,   floating:0, onworkspace:f[1]

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Allows size persistence between application launches for floating windows
windowrule = persistentsize, floating:1

# Floating apps
windowrule = float, class:1password
windowrule = float, class:evolution-alarm-notify
windowrule = float, class:blueman-applet
windowrule = float, class:re.sonny.Junction
windowrule = float, class:gcm-picker
windowrule = float, class:org.gnome.Calculator

# Browser
windowrule = tag +browser, initialClass:^(brave-|firefox)(.*)$
windowrule = float, tag:browser, initialTitle:^(MetaMask|Keplr|Phantom Wallet|Slush)(.*)$

# Games
windowrule = content game, initialClass:^(steam_)(.*)$
windowrule = tag +game, initialClass:^(steam|net.lutris.Lutris)$
windowrule = tag +game, content:game
windowrule = immediate, content:game
windowrule = workspace name:gaming, tag:game

# Terminal
windowrule = tag +term, class:^(com.mitchellh.ghostty|kitty)
windowrule = noblur, tag:term
windowrule = opaque, tag:term

# clipse
windowrule = float, class:(clipse)        # ensure you have a floating window class set if you want this behavior
windowrule = size 620 650, class:(clipse) # set the size of the window as necessary

# Media
windowrule = tag +media, class:^(Spotify|de.haeckerfelix.Shortwave|vlc)
windowrule = tag +media, content:video
windowrule = workspace special:media, tag:media

# Communication
windowrule = tag +comms, class:^(signal|org.telegram.desktop|ferdium)
windowrule = workspace special:comms, tag:comms

windowrule = float, class:signal, title:(Signal Desktop Preferences)

# Mining
windowrule = tag +mining, class:^(monero-core)
windowrule = workspace special:mining, tag:mining

# Fix pinentry losing focus
windowrule = stayfocused, class:(pinentry-)(.*) 
windowrule = stayfocused, class:1password, title:(Quick Access)(.*)

# Secure input
windowrule = noscreenshare, class:^(pinentry-.*|1password)

# Fix some dragging issues with XWayland
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# Initial workspace
windowrule = workspace 1, class:org.gnome.Calendar
windowrule = workspace 1, class:^(Mailspring|me.proton.Mail)
windowrule = workspace 1, class:^(Todoist)
windowrule = workspace 2, tag:browser, title:Personal
windowrule = workspace 2, class:obsidian
windowrule = workspace 3, tag:browser, title:Development
windowrule = workspace 3, tag:term
windowrule = workspace 4, class:Slack
windowrule = workspace 4, tag:browser, title:Talus

# Adds blur to waybar
layerrule = blur, waybar
