# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Smart gaps
windowrule = border_size 0, match:float on, match:workspace f[1]
windowrule = rounding 0,   match:float on, match:workspace f[1]

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Allows size persistence between application launches for floating windows
windowrule = persistent_size true, match:float off

# Floating apps
windowrule = float on, match:class 1password
windowrule = float on, match:class evolution-alarm-notify
windowrule = float on, match:class blueman-applet
windowrule = float on, match:class re.sonny.Junction
windowrule = float on, match:class gcm-picker
windowrule = float on, match:class org.gnome.Calculator
windowrule = float on, match:class io.github.aelesbao.Kairo

# Browser
windowrule = tag +browser, match:initial_class ^(brave-|firefox)(.*)$
windowrule = float on, match:tag browser, match:initial_title ^(MetaMask|Keplr|Phantom Wallet|Slush)(.*)$

# Games
windowrule = content game, match:initial_class ^(steam_)(.*)$
windowrule = tag +game, match:initial_class ^(steam|net.lutris.Lutris)$
windowrule = tag +game, match:content game
windowrule = immediate on, match:content game
windowrule = workspace name:gaming, match:tag game

# Terminal
windowrule = tag +term, match:class ^(com.mitchellh.ghostty|kitty)
windowrule = no_blur on, match:tag term
windowrule = opaque on, match:tag term

# clipse
windowrule = float on, match:class (clipse)        # ensure you have a floating window class set if you want this behavior
windowrule = size 620 650, match:class (clipse) # set the size of the window as necessary

# Media
windowrule = tag +media, match:class ^(spotify|de.haeckerfelix.Shortwave|vlc)
windowrule = tag +media, match:content video
windowrule = workspace special:media, match:tag media

# Communication
windowrule = tag +comms, match:class ^(signal|org.telegram.desktop|ferdium)
windowrule = workspace special:comms, match:tag comms

windowrule = float on, match:class signal, match:title (Signal Desktop Preferences)

# Mining
windowrule = tag +mining, match:class ^(monero-core)
windowrule = workspace special:mining, match:tag mining

# Fix pinentry losing focus
windowrule = stay_focused on, match:class (pinentry-)(.*) 
windowrule = pin on, match:class (pinentry-)(.*) 
windowrule = stay_focused on, match:class 1password, match:title (Quick Access)(.*)
windowrule = pin on, match:class 1password, match:title (Quick Access)(.*)

# Secure input
windowrule = no_screen_share on, match:class ^(pinentry-.*|1password)

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland on, match:float on, match:fullscreen off, match:pin off

# Initial workspace
windowrule = workspace 1, match:class org.gnome.Calendar
windowrule = workspace 1, match:class ^(Mailspring|me.proton.Mail)
windowrule = workspace 1, match:class ^(Todoist)
windowrule = workspace 2, match:tag browser, match:title (Personal|Taxes|Home Lab|Crypto|Shopping)
windowrule = workspace 2, match:class obsidian
windowrule = workspace 3, match:tag browser, match:title Development
windowrule = workspace 3, match:tag term
windowrule = workspace 4, match:class Slack
windowrule = workspace 4, match:tag browser, match:title Talus

# Adds blur to waybar
layerrule = blur on, match:namespace waybar
