# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_status\
$git_state\
$git_metrics\
$docker_context\
$package\
$cmake\
$deno\
$erlang\
$golang\
$helm\
$java\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[username]
style_user = "bold fg:250"
style_root = "bold fg:197"
format = "[$user]($style) "

[hostname]
format =  "on [$hostname]($style)[:](244)"
style = "bold 141"

[directory]
style = "bold fg:75"
read_only = " "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "200"

[git_commit]
format = "[( $hash)$tag]($style) "
tag_disabled = false
tag_symbol = ""
style = "105"

[git_status]
format = """([±\\[ \
([$modified](bold 226) )\
([$staged](bold 82) )\
([$renamed](bold 155) )\
([$deleted](bold 197) )\
([$conflicted](165) )\
([$untracked](125) )\
([$stashed](80) )\
([$ahead_behind](bold 215) )\
\\]]($style) )"""
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = ""
conflicted = "⇄"
untracked = ""
modified = "⩫"
staged = "+"
renamed = "→⇢"
deleted = "×"
stashed = "≡"
style = "244"

[git_state]
format = "[ $state( $progress_current/$progress_total)]($style) "
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry-picking"
bisect = "bisecting"
am = "am"
am_or_rebase = "am/rebase"
style = "bright-red"

[git_metrics]
format = "([( [ +$added](28))( [-$deleted](124))](244) )"
disabled = false

[cmd_duration]
format = "took [$duration]($style) "
style = "yellow"

[docker_context]
only_with_files = false
symbol = " "
style = "31"

[golang]
format = "via [$symbol($version )]($style)"
symbol = " "

[[battery.display]]
threshold = 20

[sudo]
format = "[$symbol sudo]($style) "
symbol = ""
style = "bold red"
disabled = false

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
