# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$deno\
$erlang\
$golang\
$helm\
$java\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[[battery.display]]
threshold = 20
