# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

format = """
$os\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_status\
$git_state\
$docker_context\
$package\
$cmake\
$deno\
$erlang\
$golang\
$helm\
$java\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[os]
format = "[$symbol](bold fg:250)"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[username]
style_user = "bold fg:250"
style_root = "bold fg:197"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format = "on [$hostname]($style) "
style = "bold 141"
ssh_only = true
disabled = false

[directory]
style = "bold fg:75"
read_only = "  "
read_only_style = "197"
truncation_length = 1
truncation_symbol = "…/"
home_symbol = "󰋜 ~"
format = "at [$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[](purple)"
error_symbol = "[](red)"
# vicmd_symbol = "[❮](green)"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "200"

[git_commit]
format = "[( $hash$tag)]($style) "
only_detached = true
tag_disabled = false
tag_symbol = "  "
style = "105"

[git_status]
format = """([±\\[ \
([$modified](bold 226) )\
([$staged](bold 82) )\
([$renamed](bold 155) )\
([$deleted](bold 197) )\
([$conflicted](202) )\
([$untracked](125) )\
([$stashed](80) )\
([$ahead_behind](bold 215) )\
\\]]($style) )"""
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = ""
conflicted = "⇄"
untracked = ""
modified = "⩫"
staged = "+"
renamed = "➔"
deleted = "×"
stashed = "≡"
style = "244"

[git_state]
format = "[ $state( $progress_current/$progress_total)]($style) "
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry-picking"
bisect = "bisecting"
am = "am"
am_or_rebase = "am/rebase"
style = "bright-red"

[git_metrics]
format = "([([ +$added](28))([ -$deleted](124))](244) )"
disabled = false

[cmd_duration]
format = "took [$duration]($style) "
style = "yellow"

[docker_context]
only_with_files = false
symbol = " "
style = "31"

[golang]
format = "via [$symbol($version )]($style)"
symbol = " "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰁾 "

[[battery.display]]
threshold = 10
charging_symbol = "󰂆 "
discharging_symbol = "󰁺 "
style = "bold red"

#[[battery.display]]
#threshold = 20
#charging_symbol = "󰂆 "
#discharging_symbol = "󰁻 "
#style = "bold yellow"

[[battery.display]]
threshold = 30
charging_symbol = "󰂇 "
discharging_symbol = "󰁼 "
style = "fg:178"

[sudo]
format = "[$symbol sudo]($style) "
symbol = ""
style = "bold red"
disabled = false

[aws]
symbol = "  "

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
symbol = "󱃾 "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "
