# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

format = """
$os\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_status\
$git_state\
$docker_context\
$package\
$cmake\
$deno\
$erlang\
$golang\
$helm\
$java\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$sudo\
$time\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"

[os]
format = "[$symbol](fg:overlay2)"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[username]
style_user = "bold fg:text"
style_root = "bold fg:red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format = "on [$hostname]($style) "
style = "bold fg:lavender"
ssh_only = true
disabled = false

[directory]
style = "bold fg:blue"
format = "at [$path]($style)[$read_only]($read_only_style) "
home_symbol = "󰋜 ~"
read_only = "  "
read_only_style = "fg:red dimmed"
truncation_length = 4
truncation_symbol = "…/"
before_repo_root_style = "bold fg:blue"
repo_root_style = "bold fg:blue"
repo_root_format = "at [ ]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) "

[directory.substitutions]
"Desktop" = " Desktop"
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Dropbox" = " Dropbox"
"Movies" = "󰿎 Movies"
"Music" = "󱍙 Music"
"Pictures" = "󰉏 Pictures"
"workspace" = " workspace"

[shell]
format = "[$indicator]($style)"
style = "lavender dimmed"
bash_indicator = " "
fish_indicator = "󰈺 "
zsh_indicator = ""
disabled = false

[character]
success_symbol = "[](fg:lavender)"
error_symbol = "[](fg:red)"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "fg:mauve"

[git_commit]
format = "[( $hash$tag)]($style) "
only_detached = true
tag_disabled = false
tag_symbol = "  "
style = "fg:pink"

[git_status]
format = """([ \
([$modified](bold fg:yellow) )\
([$staged](bold fg:green) )\
([$renamed](bold fg:teal) )\
([$deleted](bold fg:red) )\
([$conflicted](fg:red) )\
([$untracked](fg:sky dimmed) )\
([$stashed](fg:sapphire) )\
([$ahead_behind](bold fg:peach) )\
]($style))"""
ahead      = "⇡"
behind     = "⇣"
diverged   = "⇵"
conflicted = "⇄"
up_to_date = "[󰄵](bold fg:green)"
untracked  = ""
modified   = ""
staged     = ""
renamed    = ""
deleted    = ""
stashed    = ""
style      = "fg:text dimmed"

[git_state]
format = "[ $state( $progress_current/$progress_total)]($style) "
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry-picking"
bisect = "bisecting"
am = "am"
am_or_rebase = "am/rebase"
style = "fg:maroon"

[git_metrics]
format = "([([ +$added](fg:green dimmed))([ -$deleted](fg:red dimmed))](fg:text dimmed)) "
disabled = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰁾 "

[[battery.display]]
threshold = 10
charging_symbol = "󰂆 "
discharging_symbol = "󰁺 "
style = "bold fg:red dimmed"

[[battery.display]]
threshold = 30
charging_symbol = "󰂇 "
discharging_symbol = "󰁼 "
style = "fg:yellow dimmed"

[sudo]
format = "[$symbol sudo]($style) "
symbol = ""
style = "bold fg:red"
disabled = false

[time]
time_format = "%R"               # Hour:Minute Format
style = "fg:text dimmed"
format = '[ $time]($style) '
disabled = false

[cmd_duration]
format = "([took ([$duration](fg:yellow dimmed))]($style)) "
style = "fg:text dimmed"

[aws]
symbol = "  "

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
only_with_files = false
symbol = " "
style = "bold fg:#1d63ed"

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
format = "[$symbol($version)]($style) "
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
symbol = "󱃾 "
style = "bold fg:#326ce5"

[memory_usage]
symbol = "󰍛 "
style = "bold fg:overlay1"
format = "using [$symbol${ram}( | ${swap})]($style) "
disabled = true

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
