# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

format = """
$os\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_status\
$git_state\
$docker_context\
$package\
$cmake\
$deno\
$erlang\
$golang\
$helm\
$java\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$vagrant\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$sudo\
$time\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character\
"""

palette = 'cyberwave'

# Pallete based on Tokyo Night Moon (https://github.com/folke/tokyonight.nvim)
[palettes.cyberwave]
black = "#1b1d2b"
red = "#db4b4b"
green = "#9ece6a"
yellow = "#ff9e64"
blue = "#7aa2f7"
magenta = "#af87ff"
cyan = "#7dcfff"
white = "#a9b1d6"
bright-black = "#444a73"
bright-red = "#ff757f"
bright-green = "#c3e88d"
bright-yellow = "#ffc777"
bright-blue = "#82aaff"
bright-magenta = "#c099ff"
bright-cyan = "#86e1fc"
bright-white = "#c8d3f5"

# extended colors
rot = "#c53b53"
grey = "#828bb8"
full-white = "#ffffff"
neon-3 = "#ff5f00"
neon-1 = "#f000d9"
neon-2 = "#0abdc6"

[os]
format = "[$symbol](fg:white)"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[username]
style_user = "bold fg:full-white"
style_root = "bold fg:bright-red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format = "on [$hostname]($style) "
style = "bold fg:magenta"
ssh_only = true
disabled = false

[directory]
style = "bold fg:blue"
format = "at [$path]($style)[$read_only]($read_only_style) "
home_symbol = "󰋜 ~"
read_only = "  "
read_only_style = "fg:bright-red"
truncation_length = 4
truncation_symbol = "…/"
before_repo_root_style = "bold fg:magenta"
repo_root_style = "bold fg:magenta"
repo_root_format = "at [ ]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) "

[directory.substitutions]
"Desktop" = " Desktop"
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Dropbox" = " Dropbox"
"Movies" = "󰿎 Movies"
"Music" = "󱍙 Music"
"Pictures" = "󰉏 Pictures"
"workspace" = " workspace"

[character]
success_symbol = "[](fg:purple)"
error_symbol = "[](fg:red)"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "fg:neon-1"

[git_commit]
format = "[( $hash$tag)]($style) "
only_detached = true
tag_disabled = false
tag_symbol = "  "
style = "fg:bright-magenta"

[git_status]
format = """([±\\[ \
([$modified](bold fg:bright-yellow) )\
([$staged](bold fg:bright-green) )\
([$renamed](bold fg:green) )\
([$deleted](bold fg:bright-red) )\
([$conflicted](fg:neon-3) )\
([$untracked](fg:red dimmed) )\
([$stashed](fg:neon-2) )\
([$ahead_behind](bold fg:yellow) )\
\\]]($style) )"""
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = ""
conflicted = "⇄"
untracked = ""
modified = "⩫"
staged = "+"
renamed = "➔"
deleted = "×"
stashed = "≡"
style = "fg:white dimmed"

[git_state]
format = "[ $state( $progress_current/$progress_total)]($style) "
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry-picking"
bisect = "bisecting"
am = "am"
am_or_rebase = "am/rebase"
style = "fg:bright-red"

[git_metrics]
format = "([([ +$added](fg:green dimmed))([ -$deleted](fg:red dimmed))](fg:white dimmed)) "
disabled = false

[cmd_duration]
format = "took [$duration]($style) "
style = "fg:yellow"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰁾 "

[[battery.display]]
threshold = 10
charging_symbol = "󰂆 "
discharging_symbol = "󰁺 "
style = "bold fg:red"

[[battery.display]]
threshold = 30
charging_symbol = "󰂇 "
discharging_symbol = "󰁼 "
style = "fg:yellow"

[sudo]
format = "[$symbol sudo]($style) "
symbol = ""
style = "bold fg:red"
disabled = false

[time]
disabled = false
time_format = "%R"               # Hour:Minute Format
style = "fg:white dimmed"
format = 'at [ $time]($style) '

[aws]
symbol = "  "

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
only_with_files = false
symbol = " "
style = "bold fg:#1d63ed"

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
format = "[$symbol($version)]($style) "
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
symbol = "󱃾 "
style = "bold fg:#326ce5"

[memory_usage]
symbol = "󰍛 "
style = "bold fg:grey"
format = "using [$symbol${ram}( | ${swap})]($style) "
disabled = false

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "
