[defaults]
format = "{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "focus"
name = "Focus"
duration = "25m"
time_format = "%M:%S"
command = "notify-send -u low -i cs-date-time -a 'uair' 'Pomodoro' 'Focus session finished'"

[[sessions]]
id = "short-break"
name = "Short Break"
duration = "5m"
time_format = "%M:%S"
command = "notify-send -u low -i cs-date-time -a 'uair' 'Pomodoro' 'Break session finished'"

[[sessions]]
id = "long-break"
name = "Long Break"
duration = "15m"
time_format = "%M:%S"
command = "notify-send -u low -i cs-date-time -a 'uair' 'Pomodoro' 'Break session finished'"
